[package]
name = "scraper-project"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
rand = "0.8.5"
reqwest = { version = "0.11.22", features = ["blocking"] }
scraper = "0.17.1"
serde = {version = "1.0.189", features = ["derive"]}
